name: 'PR Auto Update'
description: 'Auto update PR branch after the upstream branch is updated'
branding:
  icon: git-pull-request
  color: orange
inputs:
  token:
    description: 'The GITHUB_TOKEN secret'
    required: true
  base:
    required: true
    description: 'The base branch this action will use to get PRs'
    default: 'master'
  required_approval_count:
    required: true
    description: 'The action will skip PRs that have less approval than this value'
    default: '2'
runs:
  using: 'node12'
  main: 'dest/index.js'
