name: 'Update PR Branch'
description: 'Automatically update the branch of newest ready to merge PR. Designed to work with the auto-merge option.'
branding:
  icon: git-pull-request
  color: orange
inputs:
  token:
    description: 'The GitHub personal access token'
    required: true
  base:
    required: true
    description: 'The base branch that this action will use to get PRs'
    default: 'master'
  required_approval_count:
    required: true
    description: 'The action will skip PRs that have less approvals than this value'
    default: '2'
  require_passed_checks:
    required: false
    description: "If the action should skip PRs that have failed checks, defaults to `true`"
    default: "true"
runs:
  using: 'node12'
  main: 'dest/index.js'
