name: Unit Tests

on:
  push:
    branches: [master]
  pull_request:
    branches: ['**']

jobs:
  unit_test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: run unit test
        run: yarn test
